# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oceancd < Formula
  desc "A unified command-line interface to manage your Spot by NetApp Oceancd resources."
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spotinst/oceancd/releases/download/v0.0.1/oceancd-darwin-amd64-0.0.1.tar.gz"
      sha256 "4c706d1d84db74c7e57ffb337860bafa3633bd85d4bcb761b3d290968aa1b2ff"

      def install
        bin.install "oceancd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spotinst/oceancd/releases/download/v0.0.1/oceancd-darwin-arm64-0.0.1.tar.gz"
      sha256 "868db82467c73ef5deb8f162211f5cee3b6044cd54fabee8d2c0a5ba8d522f16"

      def install
        bin.install "oceancd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/spotinst/oceancd/releases/download/v0.0.1/oceancd-linux-amd64-0.0.1.tar.gz"
      sha256 "7407efbd29b30ce9d780157fa735f28fc3cd26d71333cfb932aad99544ff0b07"

      def install
        bin.install "oceancd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spotinst/oceancd/releases/download/v0.0.1/oceancd-linux-arm64-0.0.1.tar.gz"
      sha256 "3670117b9ae7c0ed3277c297fa4dc1295f8981db0e4fb6993d19d271f7b6d986"

      def install
        bin.install "oceancd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/spotinst/oceancd/releases/download/v0.0.1/oceancd-linux-arm-0.0.1.tar.gz"
      sha256 "80e8d17535c316722e84cc1bc7c45401155bb1f4f88e23ee41d7a6308a884bca"

      def install
        bin.install "oceancd"
      end
    end
  end
end
