# This file was generated by GoReleaser. DO NOT EDIT.
class Spotctl < Formula
  desc "A unified command-line interface to manage your Spotinst resources."
  homepage "https://api.spotinst.com/"
  version "0.0.13"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/spotinst/spotinst-cli/releases/download/v0.0.13/spotctl-darwin-amd64-0.0.13.tar.gz"
    sha256 "ec74215e79b91310eb8c9977e08e810ca94e131e31b48abca0f5df2bb9f51ddf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/spotinst/spotinst-cli/releases/download/v0.0.13/spotctl-linux-amd64-0.0.13.tar.gz"
      sha256 "9de254be017180bbb2f9ddf5c764b3638f9cd1b824e650bd974ceca4b426eedf"
    end
  end

  def install
    bin.install "spotctl"
  end
end
